import { useTradeStore } from "@/stores/tradeStore";
import { Brain, BarChart3, Loader2 } from "lucide-react";
import { clsx } from "clsx";

export function ResearchPanel() {
  const { researchEntries, technicalAnalysis, researchLoading, selectedSymbol } =
    useTradeStore();

  return (
    <div className="flex flex-col overflow-hidden" style={{ maxHeight: "45%" }}>
      <div className="p-3 border-b border-surface-border shrink-0">
        <div className="flex items-center gap-2 mb-2">
          <Brain className="w-4 h-4 text-accent" />
          <span className="panel-header flex-1">AI Research</span>
          {researchLoading && <Loader2 className="w-3 h-3 text-text-muted animate-spin" />}
        </div>

        {technicalAnalysis && (
          <div className="text-xs space-y-1.5">
            <div className="flex items-center gap-2">
              <span className="text-text-primary font-semibold text-sm">
                ${technicalAnalysis.current_price.toLocaleString(undefined, {
                  minimumFractionDigits: 2,
                  maximumFractionDigits: 2,
                })}
              </span>
              {technicalAnalysis.price_change_24h != null && (
                <span
                  className={clsx(
                    "text-xs font-medium",
                    technicalAnalysis.price_change_24h >= 0 ? "text-positive" : "text-negative",
                  )}
                >
                  {technicalAnalysis.price_change_24h >= 0 ? "+" : ""}
                  {technicalAnalysis.price_change_24h.toFixed(2)}%
                </span>
              )}
            </div>
            <p className="text-text-secondary leading-relaxed">
              {technicalAnalysis.summary}
            </p>
            <div className="flex gap-3 pt-1 flex-wrap">
              {technicalAnalysis.indicators.rsi_14 != null && (
                <span className="text-text-muted">
                  RSI:{" "}
                  <span
                    className={clsx(
                      "font-mono",
                      Number(technicalAnalysis.indicators.rsi_14) > 70
                        ? "text-negative"
                        : Number(technicalAnalysis.indicators.rsi_14) < 30
                          ? "text-positive"
                          : "text-text-primary",
                    )}
                  >
                    {String(technicalAnalysis.indicators.rsi_14)}
                  </span>
                </span>
              )}
              {technicalAnalysis.support_resistance.resistance.length > 0 && (
                <span className="text-text-muted">
                  R: <span className="text-negative font-mono">
                    ${technicalAnalysis.support_resistance.resistance[0].toLocaleString()}
                  </span>
                </span>
              )}
              {technicalAnalysis.support_resistance.support.length > 0 && (
                <span className="text-text-muted">
                  S: <span className="text-positive font-mono">
                    ${technicalAnalysis.support_resistance.support[0].toLocaleString()}
                  </span>
                </span>
              )}
            </div>
          </div>
        )}
      </div>

      <div className="flex-1 overflow-y-auto p-3 space-y-2">
        {researchEntries.length === 0 && !researchLoading && (
          <div className="text-center py-8 text-text-muted">
            <BarChart3 className="w-8 h-8 mx-auto mb-2 opacity-30" />
            <p className="text-xs">No research yet for {selectedSymbol}</p>
            <p className="text-xs mt-1">Research is generated by the AI agent</p>
          </div>
        )}

        {researchEntries.map((entry) => (
          <div key={entry.id} className="bg-surface rounded-md p-2.5 border border-surface-border">
            <div className="flex items-start justify-between gap-2 mb-1">
              <span className="text-xs font-medium text-text-primary leading-tight">
                {entry.title}
              </span>
              {entry.sentiment && (
                <span
                  className={clsx(
                    "text-[10px] font-semibold px-1.5 py-0.5 rounded shrink-0",
                    entry.sentiment === "bullish"
                      ? "bg-positive/10 text-positive"
                      : entry.sentiment === "bearish"
                        ? "bg-negative/10 text-negative"
                        : "bg-yellow-500/10 text-yellow-500",
                  )}
                >
                  {entry.sentiment}
                </span>
              )}
            </div>
            <p className="text-xs text-text-secondary leading-relaxed line-clamp-3">
              {entry.summary}
            </p>
            <div className="flex items-center gap-2 mt-1.5 text-[10px] text-text-muted">
              <span>{new Date(entry.created_at).toLocaleDateString()}</span>
              {entry.confidence != null && (
                <>
                  <span>·</span>
                  <span>{(entry.confidence * 100).toFixed(0)}% confidence</span>
                </>
              )}
              <span>·</span>
              <span className="capitalize">{entry.report_type.replace("_", " ")}</span>
            </div>
          </div>
        ))}

        {researchLoading && researchEntries.length === 0 && (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="w-5 h-5 text-text-muted animate-spin" />
          </div>
        )}
      </div>
    </div>
  );
}
